const translations = {
    "Reciepts" : "Paragon",
    "Company Detail" : "Dane firma",
    "Product Information" : "Produkt",
    "Print" : "Drukuj",
    "Date Of Issue": "Data wystawienia",
    "Sale Date": "Data sprzedaży",
    "Payment Deadline": "Termin płatności",
    "series": "Seria",
    "Payment Method" : "Metoda płatności",
    "Cash": "Gotówka",
    "Transfer": "przelew",
    "Compensation": "kompensata",
    "Cash On delivery" : "za pobraniem",
    "Credit / Debit Card" : "karta płatnicza",
    "All Paid" : "Zapłacono",
    "Yes": "Tak",
    "No":"Nie",
    "Invoice Date": "Data rozliczenia faktury",
    "Product Detail" : "Dane Produkt ",
    "Add More product": "Nowy wiersz",
    "Product": "Produkt",
    "PKWiU" : "PKWiU",
    "Unit": "Jedn.",
    "Quantity": "Ilość ",
    "Discount%": "Rabat %",
    "Rate": "Stawka",
    "Worth Net" : "Wart. netto",
    "Worth Gross":"Wart. brutto",
    "GTU":"GTU",
    "Action" : "Action",
    "name": "Nazwa pełna",
    "pkwiu": "pkwiu",
    "unit": " Jedn ",
    "qty": " Ilość ",
    "discount": " Rabat ",
    "rate": " Stawka ",
    "worthNet": " Wart. netto ",
    "worthGross": " Wart. brutto",
    "gtu": "GTU",
    "remove": " Usunąć ",
    "description": "Opis",
    "nip": "NIP",
    "Full Name": " Nazwa pełna ",
    "Short Name": " Nazwa skrócona ",
    "email": " Adres e-mail ",
    "taxId":" NIP Identyfikator ",
    "id": " Identyfikator ",
    "Code": "Kod",
    "City": "Miasto",
    "Street, House flat": " Ulica, dom / lokal ",
    "Country": "Kraj",
    "Bank Acount Name" : " Nazwę banku ",
    "Bank Account Number": " Nr Konto bankowe ",
    "Enter logo url": " Wpisz adres URL logo ",
    "Generate pdf" : " Drukuj plik PDF",
    "Net Price" : "Net Price"
};

export const translate = (key, lang) => {
    if(lang === "pl") {
        return translations[key]
    } else {
        return key;
    }
};