const translations = {
    "Reciepts" : "Reciep",
    "Company Detail" : "Company Detail",
    "Product Information" : "Product Information",
    "Print" : "Print",
    "Date Of Issue": "Date Of Issue",
    "Sale Date": "Sale Date",
    "Payment Deadline": "Payment Deadline",
    "series": "series",
    "Payment Method" : "Payment Method",
    "Cash": "Cash",
    "Transfer": "Transfer",
    "Compensation": "Compensation",
    "On delivery" : "On delivery",
    "Credit / Debit Card" : "Credit / Debit Card",
    "All Paid" : "All Paid",
    "Yes": "Yes",
    "No":"No",
    "Invoice Date": "Invoice Date",
    "Product Detail" : "Product Detail",
    "Add More product": "Add More product",
    "Product": "Product",
    "PKWiU" : "PKWiU",
    "Unit": "Unit",
    "Quantity": "Quantity",
    "Discount%": "Discount%",
    "Rate": "Rate",
    "Worth Net" : "Worth Net",
    "Worth Gross":"Worth Gross",
    "GTU":"GTU",
    "Action" : "Action",
    "name": "name",
    "pkwiu": "pkwiu",
    "unit": "unit",
    "qty": "qty",
    "discount": "discount",
    "rate": "rate",
    "worthNet": "worthNet",
    "worthGross": "worthGross",
    "gtu": "gtu",
    "remove": "remove",
    "description": "description",
    "nip": "nip",
    "Full Name": "Full Name",
    "Short Name": "Short Name",
    "email": "email",
    "taxId":"taxId",
    "id": "id",
    "Code": "Code",
    "City": "City",
    "Street, House flat": "Street, House flat",
    "Country": "Country",
    "Bank Acount Name" : "Bank Acount Name",
    "Bank Account Number": "Bank Account Number",
    "Enter logo url": "Enter logo url",
    "Generate pdf" : "Generate pdf"
};

export const translate = (key, lang) => {
    if(lang === "pl") {
        return translations[key]
    } else {
        return key;
    }
};